# Generated by Django 5.1.15 on 2026-09-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_unique_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='counted',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
