# Generated by Django 5.1.15 on 2026-09-23 06:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ur', models.CharField(blank=True, default='', max_length=200)),
                ('body_en', models.TextField()),
                ('body_ur', models.TextField(blank=True, default='')),
                ('days_needed', models.PositiveSmallIntegerField(default=14)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('provider', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('pakistan', 'Pakistan'), ('abroad', 'Abroad')], max_length=10)),
                ('country', models.CharField(default='Pakistan', max_length=60)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ur', models.CharField(blank=True, default='', max_length=200)),
                ('summary_en', models.TextField()),
                ('summary_ur', models.TextField(blank=True, default='')),
                ('coverage_en', models.TextField()),
                ('coverage_ur', models.TextField(blank=True, default='')),
                ('who_for_en', models.TextField()),
                ('who_for_ur', models.TextField(blank=True, default='')),
                ('application_steps_en', models.TextField()),
                ('application_steps_ur', models.TextField(blank=True, default='')),
                ('family_summary_en', models.TextField()),
                ('family_summary_ur', models.TextField(blank=True, default='')),
                ('levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None)),
                ('covers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('funding', models.CharField(choices=[('full', 'Fully funded'), ('partial', 'Partial'), ('tuition_only', 'Tuition only'), ('stipend_only', 'Stipend only')], default='partial', max_length=20)),
                ('women_only', models.BooleanField(default=False)),
                ('female_quota', models.BooleanField(default=False)),
                ('allows_other_scholarship', models.BooleanField(default=False)),
                ('university_type', models.CharField(choices=[('any', 'Any'), ('public', 'Public'), ('private', 'Private'), ('partner', 'Partner universities')], default='any', max_length=10)),
                ('provinces', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('income_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('test_requirement', models.CharField(choices=[('required', 'Required'), ('waiver_possible', 'Waiver possible'), ('none', 'None')], default='none', max_length=20)),
                ('special_categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('required_documents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('requirements', models.JSONField(default=list)),
                ('usual_opening_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('expected', 'Expected')], default='expected', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('official_link', models.URLField()),
                ('last_verified', models.DateField()),
                ('next_check', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarships.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.URLField(blank=True, default='')),
                ('note', models.TextField()),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='scholarships.scholarship')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
