# Generated by Django 5.1.15 on 2026-09-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
