# Generated by Django 5.1.15 on 2026-09-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_alter_scholarship_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
