# Generated by Django 5.1.15 on 2026-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_problemreport_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='seed_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='seed_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
    ]
