import { B, API, ok, open } from "./lib.mjs";
const { browser, page, errors } = await open(null);
const count = async () => (await (await fetch(`${API}/counters`)).json()).family_shared;
await page.goto(`${B}/en/scholarships/peef-undergraduate`);
await page.getByRole("link", { name: "Page for my parents" }).click();
await page.waitForURL(/\/ur\/family\/peef-undergraduate/);
await page.waitForSelector("h1");
ok((await page.locator("html").getAttribute("dir")) === "rtl", "family page opens in Urdu, RTL");
ok((await page.locator("h1").innerText()).includes("والدین کے لیے معلومات"), "urdu heading");
ok((await page.locator("article").innerText()).includes("حکومتِ پنجاب"), "urdu family summary");
const before = await count();
const [popup] = await Promise.all([page.waitForEvent("popup"), page.getByRole("button", { name: "واٹس ایپ پر شیئر کریں" }).click()]);
ok(popup.url().includes("wa.me") || popup.url().includes("whatsapp"), `share opens WhatsApp: ${popup.url().slice(0, 60)}`);
await new Promise((r) => setTimeout(r, 500));
ok((await count()) === before + 1, "family_shared counter incremented");
await page.goto(`${B}/en/family/peef-undergraduate`);
await page.waitForSelector("text=اردو میں پڑھیں");
ok(true, "english version offers Urdu link");
ok(errors.length === 0, `no page errors ${JSON.stringify(errors)}`);
await browser.close();
